"""Tests for ``toolkit run init`` command."""

from pathlib import Path

import json

from typer.testing import CliRunner

from toolkit.cli.app import app


runner = CliRunner()


def _make_raw_dir(tmp_path: Path, dataset: str, year: int) -> None:
    """Create a minimal raw dir with a CSV file so run raw can succeed."""
    raw_dir = tmp_path / "data" / "raw" / dataset / str(year)
    raw_dir.mkdir(parents=True, exist_ok=True)
    (raw_dir / f"{dataset}_{year}.csv").write_text(
        "col1;col2;col3\nval1;val2;val3\n",
        encoding="utf-8",
    )


def _make_dataset_yml(tmp_path: Path, dataset: str, years: list[int], year_for_path: int | None = None) -> Path:
    """Create a minimal dataset.yml with a raw source that uses local_file.

    ``year_for_path`` is the year used in the raw path (defaults to first year in list).
    """
    yml = tmp_path / "dataset.yml"
    years_str = ", ".join(str(y) for y in years)
    path_year = year_for_path if year_for_path is not None else years[0]
    yml.write_text(
        f"root: {tmp_path}\n"
        f"dataset:\n"
        f"  name: {dataset}\n"
        f"  years: [{years_str}]\n"
        f"raw:\n"
        f"  sources:\n"
        f"    - type: local_file\n"
        f"      args:\n"
        f"        path: data/raw/{dataset}/{path_year}/{dataset}_{path_year}.csv\n"
        f"clean:\n"
        f"  sql: sql/clean.sql\n",
        encoding="utf-8",
    )
    return yml


def _make_profile(tmp_path: Path, dataset: str, year: int) -> None:
    """Create a raw profile so scaffold can work."""
    profile_dir = tmp_path / "data" / "raw" / dataset / str(year) / "_profile"
    profile_dir.mkdir(parents=True, exist_ok=True)
    profile = {
        "dataset": dataset,
        "year": year,
        "file_used": f"{dataset}_{year}.csv",
        "encoding_suggested": "utf-8",
        "delim_suggested": ";",
        "decimal_suggested": None,
        "skip_suggested": 0,
        "robust_read_suggested": False,
        "header_line": "col1;col2;col3",
        "columns_raw": ["col1", "col2", "col3"],
        "columns_norm": ["col1", "col2", "col3"],
        "missingness_top": [],
        "sample_rows": [],
        "mapping_suggestions": {
            "col1": {"from": "col1", "type": "str"},
            "col2": {"from": "col2", "type": "int"},
            "col3": {"from": "col3", "type": "double"},
        },
        "warnings": [],
    }
    (profile_dir / "profile.json").write_text(json.dumps(profile), encoding="utf-8")


# --- unit helpers for clean scaffold ---


def _scaffold_clean_sql(tmp_path: Path, dataset: str, year: int) -> Path:
    """Create a minimal clean.sql file."""
    sql_dir = tmp_path / "sql"
    sql_dir.mkdir(parents=True, exist_ok=True)
    path = sql_dir / "clean.sql"
    path.write_text("-- existing clean.sql\nSELECT 1;\n", encoding="utf-8")
    return path


# --- CLI tests ---


def test_run_init_dry_run(tmp_path: Path):
    """dry-run should print plan without touching files."""
    dataset = "init_ds"
    year = 2024
    _make_raw_dir(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    result = runner.invoke(app, ["run", "init", "-c", str(yml), "--dry-run"])

    assert result.exit_code == 0
    assert "Init bootstrap plan" in result.output
    assert "status: DRY_RUN" in result.output
    assert "raw (+ scaffold clean.sql if missing)" in result.output
    # clean.sql should NOT be created
    assert not (tmp_path / "sql" / "clean.sql").exists()


def test_run_init_scaffolds_clean_sql_when_missing(tmp_path: Path):
    """run init should scaffold clean.sql from existing raw profile."""
    dataset = "init_ds"
    year = 2024
    _make_raw_dir(tmp_path, dataset, year)
    _make_profile(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    result = runner.invoke(app, ["run", "init", "-c", str(yml)])

    assert result.exit_code == 0
    clean_sql = tmp_path / "sql" / "clean.sql"
    assert clean_sql.exists()
    assert "scaffoldato" in result.output
    content = clean_sql.read_text(encoding="utf-8")
    assert "-- Generated by toolkit scaffold clean" in content


def test_run_init_skips_clean_sql_when_already_exists(tmp_path: Path):
    """run init should NOT overwrite an existing clean.sql."""
    dataset = "init_ds"
    year = 2024
    _make_raw_dir(tmp_path, dataset, year)
    _make_profile(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    existing = _scaffold_clean_sql(tmp_path, dataset, year)
    original_content = existing.read_text(encoding="utf-8")

    result = runner.invoke(app, ["run", "init", "-c", str(yml)])

    assert result.exit_code == 0
    # File unchanged
    assert existing.read_text(encoding="utf-8") == original_content
    assert "gia esistente" in result.output or "skip" in result.output.lower()


def test_run_init_single_year_with_multi_year_config(tmp_path: Path):
    """--years should allow selecting a single year from a multi-year config."""
    dataset = "init_ds"
    _make_raw_dir(tmp_path, dataset, 2024)
    _make_raw_dir(tmp_path, dataset, 2025)
    _make_profile(tmp_path, dataset, 2024)
    yml = _make_dataset_yml(tmp_path, dataset, [2024, 2025], year_for_path=2024)

    result = runner.invoke(app, ["run", "init", "-c", str(yml), "--years", "2024"])

    assert result.exit_code == 0
    # Only 2024 clean.sql should be scaffolded
    clean_sql = tmp_path / "sql" / "clean.sql"
    assert clean_sql.exists()


def test_run_init_fails_when_profile_missing_and_no_clean_sql(tmp_path: Path):
    """When raw has no profile.json and clean.sql does not exist, run init fails.

    Uses a .zip raw source: run_raw downloads it but does NOT profile it
    (only CSV/TSV/TXT are profiled), so scaffold cannot proceed and the
    command must fail with a clear error.
    """
    dataset = "init_ds"
    year = 2024

    # Create a non-CSV raw source (zip) that won't be profiled.
    # The local_file plugin must be able to find it.
    raw_dir = tmp_path / "data" / "raw" / dataset / str(year)
    raw_dir.mkdir(parents=True, exist_ok=True)
    import zipfile
    zip_path = raw_dir / f"{dataset}_{year}.zip"
    with zipfile.ZipFile(zip_path, "w") as zf:
        zf.writestr("data.csv", "col1,col2\nval1,val2\n")

    # Create dataset.yml pointing to the zip (non-profilable)
    yml = tmp_path / "dataset.yml"
    yml.write_text(
        f"root: {tmp_path}\n"
        f"dataset:\n"
        f"  name: {dataset}\n"
        f"  years: [{year}]\n"
        f"raw:\n"
        f"  sources:\n"
        f"    - type: local_file\n"
        f"      args:\n"
        f"        path: data/raw/{dataset}/{year}/{dataset}_{year}.zip\n"
        f"clean:\n"
        f"  sql: sql/clean.sql\n",
        encoding="utf-8",
    )

    # Profile is NOT pre-created; clean.sql does NOT exist.
    result = runner.invoke(app, ["run", "init", "-c", str(yml)])

    assert result.exit_code != 0
    assert "profilo" in result.output.lower() or "profile" in result.output.lower()


def test_run_init_reports_correct_scaffold_message_when_pre_existing(tmp_path: Path):
    """When clean.sql exists before run init, message should say 'gia esistente'.

    This verifies the pre-state tracking fix: even though run_raw internally
    scaffolds, run_init should not report that it scaffolded.
    """
    dataset = "init_ds"
    year = 2024
    _make_raw_dir(tmp_path, dataset, year)
    _make_profile(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    # Pre-create clean.sql
    existing = _scaffold_clean_sql(tmp_path, dataset, year)

    result = runner.invoke(app, ["run", "init", "-c", str(yml)])

    assert result.exit_code == 0
    # Must report "gia esistente", NOT "scaffoldato"
    assert "gia esistente" in result.output
    assert "scaffoldato" not in result.output


def test_run_init_dry_run_validates_config(tmp_path: Path):
    """dry-run should validate the config and fail with a clear error if invalid."""
    dataset = "init_ds"
    year = 2024
    # Missing raw.sources - invalid config
    yml = tmp_path / "dataset.yml"
    yml.write_text(
        f"root: {tmp_path}\n"
        f"dataset:\n"
        f"  name: {dataset}\n"
        f"  years: [{year}]\n"
        f"raw:\n"  # empty raw - no sources
        f"clean:\n"
        f"  sql: sql/clean.sql\n",
        encoding="utf-8",
    )

    result = runner.invoke(app, ["run", "init", "-c", str(yml), "--dry-run"])

    # Should fail during validation (not silently succeed with a static plan)
    assert result.exit_code != 0
    assert "raw.sources" in result.output or "missing" in result.output.lower()
