from __future__ import annotations

import json
from pathlib import Path

import pytest

from toolkit.cli.app import app
from toolkit.scaffold.clean import (
    generate_clean_sql,
    propose_clean_read,
    _snake_case,
    _map_duckdb_type,
)

pytestmark = pytest.mark.contract


# --- unit tests for scaffold.clean ---


class TestSnakeCase:
    def test_simple(self):
        assert _snake_case("CodiceEnte") == "codice_ente"

    def test_spaces(self):
        assert _snake_case("Codice Ente") == "codice_ente"

    def test_special_chars(self):
        assert _snake_case("CODICE-ENTE") == "codice_ente"

    def test_already_snake(self):
        assert _snake_case("codice_ente") == "codice_ente"

    def test_empty(self):
        assert _snake_case("  ") == "  "

    def test_mixed(self):
        assert _snake_case("Denominazione_Ute") == "denominazione_ute"


class TestMapDuckdbType:
    def test_int(self):
        assert _map_duckdb_type("int") == "BIGINT"

    def test_double(self):
        assert _map_duckdb_type("double") == "DOUBLE"

    def test_date(self):
        assert _map_duckdb_type("date") == "DATE"

    def test_bool(self):
        assert _map_duckdb_type("bool") == "BOOLEAN"

    def test_str_default(self):
        assert _map_duckdb_type("str") == "VARCHAR"

    def test_unknown(self):
        assert _map_duckdb_type("weird_type") == "VARCHAR"


class TestGenerateCleanSql:
    def test_minimal_profile(self, tmp_path: Path):
        profile = {
            "file_used": "test.csv",
            "encoding_suggested": "utf-8",
            "delim_suggested": ";",
            "decimal_suggested": ",",
            "columns_raw": ["col1", "col2"],
            "mapping_suggestions": {},
            "warnings": [],
        }
        sql = generate_clean_sql(profile, "test_ds", 2024)
        assert "-- Generated by toolkit scaffold clean" in sql
        assert "SELECT" in sql
        assert "FROM raw_input" in sql
        assert "read_csv(" not in sql  # no inline read_csv call

    def test_with_mapping_suggestions(self, tmp_path: Path):
        profile = {
            "file_used": "bdap.csv",
            "encoding_suggested": "utf-8",
            "delim_suggested": ";",
            "decimal_suggested": ",",
            "header_line": "CodiceEnte;Importo",
            "skip_suggested": 0,
            "columns_raw": ["CodiceEnte", "Importo"],
            "mapping_suggestions": {
                "CodiceEnte": {"from": "CodiceEnte", "type": "str"},
                "Importo": {"from": "Importo", "type": "double"},
            },
            "warnings": [],
        }
        sql = generate_clean_sql(profile, "bdap_lea", 2024)
        assert "TRY_CAST" in sql
        assert "CodiceEnte" in sql
        assert "Importo" in sql
        assert "BIGINT" in sql or "DOUBLE" in sql
        assert "codice_ente" in sql
        assert "importo" in sql
        assert "FROM raw_input" in sql
        # No inline read_csv call
        assert "read_csv(" not in sql
        assert "columns={" not in sql

    def test_header_skip_with_skip_suggested(self, tmp_path: Path):
        """Header/skip logic is now in propose_clean_read, not in SQL."""
        profile = {
            "file_used": "test.csv",
            "encoding_suggested": "utf-8",
            "delim_suggested": ";",
            "header_line": "col1;col2",
            "skip_suggested": 1,
            "columns_raw": ["col1", "col2"],
            "mapping_suggestions": {
                "col1": {"from": "col1", "type": "str"},
                "col2": {"from": "col2", "type": "int"},
            },
            "warnings": [],
        }
        sql = generate_clean_sql(profile, "test", 2024)
        assert "FROM raw_input" in sql

    def test_no_columns_keeps_header_true(self, tmp_path: Path):
        """When truly no columns available, SQL is pure transformation."""
        profile = {
            "file_used": "test.csv",
            "delim_suggested": ",",
            "header_line": "a,b",
            "skip_suggested": 0,
            "columns_raw": [],
            "mapping_suggestions": {},
            "warnings": [],
        }
        sql = generate_clean_sql(profile, "test", 2024)
        assert "FROM raw_input" in sql
        assert "read_csv" not in sql
        assert "anno" in sql
        assert "{year}::INTEGER" in sql

    def test_anno_not_injected_when_present_in_raw(self, tmp_path: Path):
        """When the raw CSV already has a column that normalizes to 'anno', scaffold does NOT inject a duplicate."""
        profile = {
            "file_used": "test.csv",
            "delim_suggested": ",",
            "header_line": "anno,regione",
            "skip_suggested": 0,
            "columns_raw": ["anno", "regione"],
            "mapping_suggestions": {
                "anno": {"from": "anno", "type": "int"},
                "regione": {"from": "regione", "type": "str"},
            },
            "warnings": [],
        }
        sql = generate_clean_sql(profile, "test", 2024)
        # Scaffold must NOT inject 2024::INTEGER when raw CSV already has 'anno'
        assert "2024::INTEGER" not in sql
        # The mapping provides 'anno' normally; no duplicate injection
        assert "anno" in sql  # from TRY_CAST


# --- unit tests for propose_clean_read ---


class TestProposeCleanRead:
    def test_with_mapping(self):
        profile = {
            "delim_suggested": ";",
            "encoding_suggested": "utf-8",
            "decimal_suggested": ",",
            "header_line": "col1;col2",
            "skip_suggested": 0,
            "mapping_suggestions": {
                "col1": {"from": "col1", "type": "str"},
                "col2": {"from": "col2", "type": "int"},
            },
        }
        result = propose_clean_read(profile)
        assert result["delim"] == ";"
        assert result["encoding"] == "utf-8"
        assert result["decimal"] == ","
        assert "columns" not in result  # header: true → no columns needed
        assert result["header"] is True  # mapping matches header → header: true
        assert result.get("skip", 0) == 0  # no skip needed with header: true

    def test_no_mapping_no_columns(self):
        profile = {
            "delim_suggested": ",",
            "header_line": "a,b",
            "skip_suggested": 0,
            "columns_raw": ["a", "b"],
            "mapping_suggestions": {},
        }
        result = propose_clean_read(profile)
        assert "columns" not in result
        assert result["header"] is True  # no explicit columns
        assert result["delim"] == ","

    def test_skip_with_header_and_preamble(self):
        """When header_line present and mapping keys match: header:true, skip preserved."""
        profile = {
            "delim_suggested": ";",
            "header_line": "col1;col2",
            "skip_suggested": 1,
            "mapping_suggestions": {
                "col1": {"from": "col1", "type": "str"},
                "col2": {"from": "col2", "type": "str"},
            },
        }
        result = propose_clean_read(profile)
        # header names match mapping keys → header:true, skip stays as-is
        assert result["header"] is True
        assert result.get("skip", 0) == 1  # skip_suggested preserved

    def test_skip_preserved_without_header(self):
        """When no header_line but skip_suggested > 0, skip is preserved."""
        profile = {
            "delim_suggested": ";",
            "skip_suggested": 3,
            "mapping_suggestions": {
                "col1": {"from": "col1", "type": "str"},
            },
        }
        result = propose_clean_read(profile)
        assert result["skip"] == 3

    def test_robust_suggested_no_mode_in_read(self):
        """robust_read_suggested does NOT produce a key inside clean.read.
        It should be set as clean.read_mode instead."""
        profile = {
            "delim_suggested": ";",
            "robust_read_suggested": True,
            "mapping_suggestions": {},
            "warnings": [],
        }
        result = propose_clean_read(profile)
        # No mode inside clean.read
        assert "mode" not in result

    def test_output_is_loadable_by_clean_read_config(self):
        """propose_clean_read output is valid for CleanReadConfig (no extra keys, correct types)."""
        from toolkit.core.config_models.clean import CleanReadConfig

        profile = {
            "delim_suggested": ",",
            "encoding_suggested": "utf-8",
            "decimal_suggested": ",",
            "header_line": "col1,col2,col3",
            "skip_suggested": 0,
            "mapping_suggestions": {
                "col1": {"from": "col1", "type": "str"},
                "col2": {"from": "col2", "type": "int"},
                "col3": {"from": "col3", "type": "double"},
            },
        }
        proposed = propose_clean_read(profile)
        # Must not raise pydantic.ValidationError
        config = CleanReadConfig(**proposed)
        assert config.delim == ","
        assert config.decimal == ","
        # header:true perché mapping matcha header_line → columns auto-detected
        assert config.header is True
        assert config.columns is None

    def test_maps_duckdb_types_correctly(self):
        profile = {
            "delim_suggested": ",",
            "mapping_suggestions": {
                "int_col": {"from": "int_col", "type": "int"},
                "float_col": {"from": "float_col", "type": "double"},
                "date_col": {"from": "date_col", "type": "date"},
                "bool_col": {"from": "bool_col", "type": "bool"},
                "str_col": {"from": "str_col", "type": "str"},
            },
        }
        result = propose_clean_read(profile)
        cols = result["columns"]
        assert cols["int_col"] == "BIGINT"
        assert cols["float_col"] == "DOUBLE"
        assert cols["date_col"] == "DATE"
        assert cols["bool_col"] == "BOOLEAN"
        assert cols["str_col"] == "VARCHAR"

    @pytest.mark.policy
    def test_header_detected_when_names_differ_from_mapping(self):
        """When header_line has real names but mapping has generic columnXX,
        propose header:true and drop the generic columns mapping.
        This is the real bug: profiler read header as data with header=false."""
        profile = {
            "delim_suggested": ";",
            "header_line": "CodiceEnte;Importo",
            "skip_suggested": 0,
            "mapping_suggestions": {
                "column01": {"from": "column01", "type": "str"},
                "column02": {"from": "column02", "type": "str"},
            },
        }
        result = propose_clean_read(profile)
        # Header has real names that differ from generic columnXX → header=true
        assert result["header"] is True
        # columns should be dropped since we now use real header
        assert "columns" not in result
        # skip stays 0 (no bump needed, header line is now recognized as header)
        assert result.get("skip", 0) == 0

    @pytest.mark.policy
    def test_header_detected_with_column_prefix_mapping(self):
        """Same as above but with 'col' prefix instead of 'column' prefix."""
        profile = {
            "delim_suggested": ";",
            "header_line": "Regione;Provincia;Comune",
            "skip_suggested": 0,
            "mapping_suggestions": {
                "col1": {"from": "col1", "type": "str"},
                "col2": {"from": "col2", "type": "str"},
                "col3": {"from": "col3", "type": "str"},
            },
        }
        result = propose_clean_read(profile)
        # "Regione" != "col1" after normalization → header detected
        assert result["header"] is True
        assert "columns" not in result

    @pytest.mark.policy
    def test_no_header_false_positive_from_numeric_first_row(self):
        """A positional CSV with first row as data (no real header) must NOT
        trigger header:true even if names differ from column01/02.
        Real header identifiers contain at least one letter."""
        profile = {
            "delim_suggested": ";",
            "header_line": "1;2;3",  # numeric data, not a real header
            "skip_suggested": 0,
            "mapping_suggestions": {
                "column01": {"from": "column01", "type": "str"},
                "column02": {"from": "column02", "type": "str"},
                "column03": {"from": "column03", "type": "str"},
            },
        }
        result = propose_clean_read(profile)
        # Numeric "1;2;3" has no letters → not treated as real header
        assert result["header"] is False
        assert result.get("columns") is not None  # columns preserved


# --- CLI integration tests ---


def _make_profile_dir(tmp_path: Path, dataset: str, year: int) -> Path:
    """Create a minimal raw profile in the expected location."""
    profile_dir = tmp_path / "data" / "raw" / dataset / str(year) / "_profile"
    profile_dir.mkdir(parents=True, exist_ok=True)
    profile = {
        "dataset": dataset,
        "year": year,
        "file_used": f"{dataset}.csv",
        "encoding_suggested": "utf-8",
        "delim_suggested": ";",
        "decimal_suggested": ",",
        "skip_suggested": 0,
        "robust_read_suggested": False,
        "header_line": "col1;col2;col3",
        "columns_raw": ["col1", "col2", "col3"],
        "columns_norm": ["col1", "col2", "col3"],
        "missingness_top": [],
        "sample_rows": [],
        "mapping_suggestions": {
            "col1": {"from": "col1", "type": "str"},
            "col2": {"from": "col2", "type": "int"},
            "col3": {"from": "col3", "type": "double"},
        },
        "warnings": [],
    }
    (profile_dir / "raw_profile.json").write_text(json.dumps(profile), encoding="utf-8")
    return profile_dir


def _make_dataset_yml(tmp_path: Path, dataset: str, years: list[int]) -> Path:
    """Create a minimal dataset.yml."""
    yml = tmp_path / "dataset.yml"
    years_str = ", ".join(str(y) for y in years)
    yml.write_text(
        f"root: {tmp_path}\ndataset:\n  name: {dataset}\n  years: [{years_str}]\nclean:\n  sql: sql/clean.sql\n",
        encoding="utf-8",
    )
    return yml


def test_scaffold_clean_dry_run(tmp_path: Path, runner):
    dataset = "test_ds"
    year = 2024
    _make_profile_dir(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml), "--dry-run"],
    )
    assert result.exit_code == 0
    assert "-- Generated by toolkit scaffold clean" in result.output
    assert "SELECT" in result.output
    assert "FROM raw_input" in result.output
    assert "read_csv(" not in result.output


def test_scaffold_clean_writes_file(tmp_path: Path, runner):
    dataset = "test_ds"
    year = 2024
    _make_profile_dir(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml)],
    )
    assert result.exit_code == 0
    output_path = tmp_path / "sql" / "clean.sql"
    assert output_path.exists()
    content = output_path.read_text(encoding="utf-8")
    assert "Generated by toolkit scaffold clean" in content


def test_scaffold_clean_does_not_overwrite(tmp_path: Path, runner):
    dataset = "test_ds"
    year = 2024
    _make_profile_dir(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    output_path = tmp_path / "sql" / "clean.sql"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    original_content = "-- existing content"
    output_path.write_text(original_content, encoding="utf-8")

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml)],
    )
    assert result.exit_code == 0
    # File should not have been modified
    assert output_path.read_text(encoding="utf-8") == original_content


def test_scaffold_clean_custom_output(tmp_path: Path, runner):
    dataset = "test_ds"
    year = 2024
    _make_profile_dir(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    custom_path = tmp_path / "custom" / "my_clean.sql"
    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml), "-o", str(custom_path)],
    )
    assert result.exit_code == 0
    assert custom_path.exists()
    assert "Generated by toolkit scaffold clean" in custom_path.read_text(encoding="utf-8")


def test_scaffold_clean_fails_without_profile(tmp_path: Path, runner):
    dataset = "test_ds"
    year = 2024
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml)],
    )
    assert result.exit_code != 0
    assert "Esegui prima: toolkit inspect profile" in result.output


def test_scaffold_clean_fails_multiple_years_without_flag(tmp_path: Path, runner):
    dataset = "test_ds"
    _make_profile_dir(tmp_path, dataset, 2024)
    yml = _make_dataset_yml(tmp_path, dataset, [2024, 2025])

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml)],
    )
    assert result.exit_code != 0
    assert "Multiple years configured" in result.output


def test_scaffold_clean_with_year_flag(tmp_path: Path, runner):
    dataset = "test_ds"
    _make_profile_dir(tmp_path, dataset, 2024)
    yml = _make_dataset_yml(tmp_path, dataset, [2024, 2025])

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml), "--year", "2024"],
    )
    assert result.exit_code == 0
    output_path = tmp_path / "sql" / "clean.sql"
    assert output_path.exists()


def test_scaffold_clean_on_project_example(project_example: Path, runner):
    """Integration test: scaffold clean should work on the project-example dataset."""
    # Create a minimal raw CSV so profile raw can work
    raw_dir = project_example / "_smoke_out" / "data" / "raw" / "project_example" / "2022"
    raw_dir.mkdir(parents=True, exist_ok=True)
    (raw_dir / "ispra_dettaglio_comunale_2022.csv").write_text(
        "comune;provincia;regione;anno;val\nRoma;RM;Lazio;2022;100\n",
        encoding="utf-8",
    )

    # First run profile raw to generate the profile
    result = runner.invoke(
        app,
        ["inspect", "profile", "-c", str(project_example / "dataset.yml")],
    )
    assert result.exit_code == 0

    # Now scaffold clean
    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(project_example / "dataset.yml"), "--dry-run"],
    )
    assert result.exit_code == 0
    assert "Generated by toolkit scaffold clean" in result.output
    assert "SELECT" in result.output
    assert "FROM raw_input" in result.output


def test_scaffold_clean_print_read_config(tmp_path: Path, runner):
    """--print-read-config prints YAML proposal and exits without writing clean.sql."""
    dataset = "test_ds"
    year = 2024
    _make_profile_dir(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml), "--print-read-config"],
    )
    assert result.exit_code == 0
    assert "clean:" in result.output
    assert "  read:" in result.output
    assert "delim:" in result.output
    assert not (tmp_path / "sql" / "clean.sql").exists()


def test_scaffold_clean_print_read_config_no_clean_sql_written(tmp_path: Path, runner):
    """Verify --print-read-config exits early and does not touch clean.sql."""
    dataset = "test_ds"
    year = 2024
    _make_profile_dir(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    sql_path = tmp_path / "sql" / "clean.sql"
    sql_path.parent.mkdir(parents=True, exist_ok=True)
    sql_path.write_text("-- pre-existing", encoding="utf-8")

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml), "--print-read-config"],
    )
    assert result.exit_code == 0
    assert sql_path.read_text(encoding="utf-8") == "-- pre-existing"


def test_scaffold_clean_print_read_config_format(tmp_path: Path, runner):
    """Output YAML from --print-read-config is valid CleanReadConfig."""
    dataset = "test_ds"
    year = 2024
    _make_profile_dir(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml), "--print-read-config"],
    )
    assert result.exit_code == 0
    # Output must contain "clean:" and "read:" sections
    assert "clean:" in result.output
    assert "  read:" in result.output
    # Must contain valid YAML key-value pairs
    assert "delim:" in result.output
    assert "encoding:" in result.output


def test_format_clean_read_proposal_valid_yaml_structure():
    """format_clean_read_proposal produces valid YAML parseable by yaml.safe_load."""
    import yaml

    from toolkit.scaffold.clean import format_clean_read_proposal

    profile = {
        "delim_suggested": ";",
        "encoding_suggested": "utf-8",
        "decimal_suggested": ",",
        "header_line": "col1;col2;col3",
        "skip_suggested": 0,
        "mapping_suggestions": {
            "col1": {"from": "col1", "type": "str"},
            "col2": {"from": "col2", "type": "int"},
        },
    }
    output = format_clean_read_proposal(profile)
    # Must be valid YAML
    parsed = yaml.safe_load(output)
    assert "clean" in parsed
    assert "read" in parsed["clean"]
    read = parsed["clean"]["read"]
    assert read["delim"] == ";"
    assert read["encoding"] == "utf-8"
    assert read["decimal"] == ","
    # CleanReadConfig(**loaded) must not raise
    from toolkit.core.config_models.clean import CleanReadConfig

    CleanReadConfig(**read)


def test_format_clean_read_proposal_robust_read_mode_top_level():
    """When robust_read_suggested is set, read_mode: robust appears outside clean.read."""
    import yaml

    from toolkit.scaffold.clean import format_clean_read_proposal

    profile = {
        "delim_suggested": ";",
        "robust_read_suggested": True,
        "mapping_suggestions": {
            "col1": {"from": "col1", "type": "str"},
        },
    }
    output = format_clean_read_proposal(profile)
    parsed = yaml.safe_load(output)
    assert "clean" in parsed
    assert "read_mode" in parsed["clean"]
    assert parsed["clean"]["read_mode"] == "robust"
    assert "mode" not in parsed["clean"]["read"]  # no "mode" inside clean.read


def test_format_clean_read_proposal_rejects_invalid_keys():
    """If propose_clean_read returned an invalid key, CleanReadConfig validation catches it."""
    from toolkit.core.config_models.clean import CleanReadConfig
    from toolkit.scaffold.clean import propose_clean_read

    profile = {
        "delim_suggested": ";",
        "mapping_suggestions": {},
        "robust_read_suggested": True,  # This used to produce invalid "mode: robust"
    }
    proposed = propose_clean_read(profile)
    # With the fix, robust_read_suggested does NOT produce "mode" inside clean.read
    assert "mode" not in proposed
    # CleanReadConfig(**proposed) must not raise
    CleanReadConfig(**proposed)


def test_format_clean_read_proposal_yaml_special_chars():
    """Output YAML must parse correctly with special chars like comma, semicolon."""
    import yaml

    from toolkit.scaffold.clean import format_clean_read_proposal

    # Decimal comma and semicolon delimiter — these need quoting in YAML
    profile = {
        "delim_suggested": ";",
        "decimal_suggested": ",",
        "encoding_suggested": "utf-8",
        "mapping_suggestions": {},
    }
    output = format_clean_read_proposal(profile)
    parsed = yaml.safe_load(output)
    assert parsed["clean"]["read"]["delim"] == ";"
    assert parsed["clean"]["read"]["decimal"] == ","
