from pathlib import Path
import json
import shutil

from typer.testing import CliRunner

from toolkit.cli.app import app
from toolkit.scaffold.clean import (
    generate_clean_sql,
    _snake_case,
    _map_duckdb_type,
)

runner = CliRunner()


# --- unit tests for scaffold.clean ---


class TestSnakeCase:
    def test_simple(self):
        assert _snake_case("CodiceEnte") == "codice_ente"

    def test_spaces(self):
        assert _snake_case("Codice Ente") == "codice_ente"

    def test_special_chars(self):
        assert _snake_case("CODICE-ENTE") == "codice_ente"

    def test_already_snake(self):
        assert _snake_case("codice_ente") == "codice_ente"

    def test_empty(self):
        assert _snake_case("  ") == "  "

    def test_mixed(self):
        assert _snake_case("Denominazione_Ute") == "denominazione_ute"


class TestMapDuckdbType:
    def test_int(self):
        assert _map_duckdb_type("int") == "BIGINT"

    def test_double(self):
        assert _map_duckdb_type("double") == "DOUBLE"

    def test_date(self):
        assert _map_duckdb_type("date") == "DATE"

    def test_bool(self):
        assert _map_duckdb_type("bool") == "BOOLEAN"

    def test_str_default(self):
        assert _map_duckdb_type("str") == "VARCHAR"

    def test_unknown(self):
        assert _map_duckdb_type("weird_type") == "VARCHAR"


class TestGenerateCleanSql:
    def test_minimal_profile(self, tmp_path: Path):
        profile = {
            "file_used": "test.csv",
            "encoding_suggested": "utf-8",
            "delim_suggested": ";",
            "decimal_suggested": ",",
            "columns_raw": ["col1", "col2"],
            "mapping_suggestions": {},
            "warnings": [],
        }
        sql = generate_clean_sql(profile, "test_ds", 2024, tmp_path)
        assert "-- Generated by toolkit scaffold clean" in sql
        assert "SELECT" in sql
        assert "read_csv" in sql
        assert "delim=';'" in sql
        assert "encoding='utf-8'" in sql

    def test_with_mapping_suggestions(self, tmp_path: Path):
        profile = {
            "file_used": "bdap.csv",
            "encoding_suggested": "utf-8",
            "delim_suggested": ";",
            "decimal_suggested": ",",
            "header_line": "CodiceEnte;Importo",
            "skip_suggested": 0,
            "columns_raw": ["CodiceEnte", "Importo"],
            "mapping_suggestions": {
                "CodiceEnte": {"from": "CodiceEnte", "type": "str"},
                "Importo": {"from": "Importo", "type": "double"},
            },
            "warnings": [],
        }
        sql = generate_clean_sql(profile, "bdap_lea", 2024, tmp_path)
        assert "TRY_CAST" in sql
        assert "CodiceEnte" in sql
        assert "Importo" in sql
        assert "BIGINT" in sql or "DOUBLE" in sql
        assert "codice_ente" in sql
        assert "importo" in sql
        # When columns are explicit, header=false and skip bumped by 1
        assert "header=false" in sql
        assert "skip=1" in sql

    def test_header_skip_with_skip_suggested(self, tmp_path: Path):
        """When header_line exists and skip_suggested > 0 with columns, skip should be bumped."""
        profile = {
            "file_used": "test.csv",
            "encoding_suggested": "utf-8",
            "delim_suggested": ";",
            "header_line": "col1;col2",
            "skip_suggested": 1,
            "columns_raw": ["col1", "col2"],
            "mapping_suggestions": {
                "col1": {"from": "col1", "type": "str"},
                "col2": {"from": "col2", "type": "int"},
            },
            "warnings": [],
        }
        sql = generate_clean_sql(profile, "test", 2024, tmp_path)
        # header_line present + columns present -> header=false, skip=1+1=2
        assert "header=false" in sql
        assert "skip=2" in sql

    def test_no_columns_keeps_header_true(self, tmp_path: Path):
        """When truly no columns available, header stays true."""
        profile = {
            "file_used": "test.csv",
            "delim_suggested": ",",
            "header_line": "a,b",
            "skip_suggested": 0,
            "columns_raw": [],
            "mapping_suggestions": {},
            "warnings": [],
        }
        sql = generate_clean_sql(profile, "test", 2024, tmp_path)
        assert "header=true" in sql
        # With no columns, SELECT * is used
        assert "SELECT\n    *" in sql

    def test_columns_sql_is_single_line(self, tmp_path: Path):
        """Verify columns param is on same line as other params (no missing comma)."""
        profile = {
            "file_used": "test.csv",
            "delim_suggested": ";",
            "header_line": "col1;col2",
            "skip_suggested": 0,
            "columns_raw": ["col1", "col2"],
            "mapping_suggestions": {
                "col1": {"from": "col1", "type": "str"},
                "col2": {"from": "col2", "type": "int"},
            },
            "warnings": [],
        }
        sql = generate_clean_sql(profile, "test", 2024, tmp_path)
        # All params should be on the same line after read_csv(
        # Pattern: read_csv('...', ..., columns={...})
        assert "FROM read_csv(" in sql
        # The columns param should follow other params with proper comma separation
        assert "auto_detect=false, columns={" in sql


# --- CLI integration tests ---


def _make_profile_dir(tmp_path: Path, dataset: str, year: int) -> Path:
    """Create a minimal raw profile in the expected location."""
    profile_dir = tmp_path / "data" / "raw" / dataset / str(year) / "_profile"
    profile_dir.mkdir(parents=True, exist_ok=True)
    profile = {
        "dataset": dataset,
        "year": year,
        "file_used": f"{dataset}.csv",
        "encoding_suggested": "utf-8",
        "delim_suggested": ";",
        "decimal_suggested": ",",
        "skip_suggested": 0,
        "robust_read_suggested": False,
        "header_line": "col1;col2;col3",
        "columns_raw": ["col1", "col2", "col3"],
        "columns_norm": ["col1", "col2", "col3"],
        "missingness_top": [],
        "sample_rows": [],
        "mapping_suggestions": {
            "col1": {"from": "col1", "type": "str"},
            "col2": {"from": "col2", "type": "int"},
            "col3": {"from": "col3", "type": "double"},
        },
        "warnings": [],
    }
    (profile_dir / "profile.json").write_text(json.dumps(profile), encoding="utf-8")
    return profile_dir


def _make_dataset_yml(tmp_path: Path, dataset: str, years: list[int]) -> Path:
    """Create a minimal dataset.yml."""
    yml = tmp_path / "dataset.yml"
    years_str = ", ".join(str(y) for y in years)
    yml.write_text(
        f"root: {tmp_path}\ndataset:\n  name: {dataset}\n  years: [{years_str}]\nclean:\n  sql: sql/clean.sql\n",
        encoding="utf-8",
    )
    return yml


def test_scaffold_clean_dry_run(tmp_path: Path):
    dataset = "test_ds"
    year = 2024
    _make_profile_dir(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml), "--dry-run"],
    )
    assert result.exit_code == 0
    assert "-- Generated by toolkit scaffold clean" in result.output
    assert "SELECT" in result.output
    assert "read_csv" in result.output


def test_scaffold_clean_writes_file(tmp_path: Path):
    dataset = "test_ds"
    year = 2024
    _make_profile_dir(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml)],
    )
    assert result.exit_code == 0
    output_path = tmp_path / "sql" / "clean.sql"
    assert output_path.exists()
    content = output_path.read_text(encoding="utf-8")
    assert "Generated by toolkit scaffold clean" in content


def test_scaffold_clean_does_not_overwrite(tmp_path: Path):
    dataset = "test_ds"
    year = 2024
    _make_profile_dir(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    output_path = tmp_path / "sql" / "clean.sql"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    original_content = "-- existing content"
    output_path.write_text(original_content, encoding="utf-8")

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml)],
    )
    assert result.exit_code == 0
    # File should not have been modified
    assert output_path.read_text(encoding="utf-8") == original_content


def test_scaffold_clean_custom_output(tmp_path: Path):
    dataset = "test_ds"
    year = 2024
    _make_profile_dir(tmp_path, dataset, year)
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    custom_path = tmp_path / "custom" / "my_clean.sql"
    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml), "-o", str(custom_path)],
    )
    assert result.exit_code == 0
    assert custom_path.exists()
    assert "Generated by toolkit scaffold clean" in custom_path.read_text(encoding="utf-8")


def test_scaffold_clean_fails_without_profile(tmp_path: Path):
    dataset = "test_ds"
    year = 2024
    yml = _make_dataset_yml(tmp_path, dataset, [year])

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml)],
    )
    # Should fail with exit code 1
    assert result.exit_code != 0
    assert "Esegui prima: toolkit profile raw" in result.output


def test_scaffold_clean_fails_multiple_years_without_flag(tmp_path: Path):
    dataset = "test_ds"
    _make_profile_dir(tmp_path, dataset, 2024)
    yml = _make_dataset_yml(tmp_path, dataset, [2024, 2025])

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml)],
    )
    assert result.exit_code != 0
    assert "Multiple years configured" in result.output


def test_scaffold_clean_with_year_flag(tmp_path: Path):
    dataset = "test_ds"
    _make_profile_dir(tmp_path, dataset, 2024)
    yml = _make_dataset_yml(tmp_path, dataset, [2024, 2025])

    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(yml), "--year", "2024"],
    )
    assert result.exit_code == 0
    output_path = tmp_path / "sql" / "clean.sql"
    assert output_path.exists()


def test_scaffold_clean_on_project_example(tmp_path: Path):
    """Integration test: scaffold clean should work on the project-example dataset."""
    src = Path("project-example")
    dst = tmp_path / "project-example"
    shutil.copytree(src, dst)

    # Create a minimal raw CSV so profile raw can work
    raw_dir = dst / "_smoke_out" / "data" / "raw" / "project_example" / "2022"
    raw_dir.mkdir(parents=True, exist_ok=True)
    (raw_dir / "ispra_dettaglio_comunale_2022.csv").write_text(
        "comune;provincia;regione;anno;val\nRoma;RM;Lazio;2022;100\n",
        encoding="utf-8",
    )

    # First run profile raw to generate the profile
    result = runner.invoke(
        app,
        ["profile", "raw", "-c", str(dst / "dataset.yml")],
    )
    assert result.exit_code == 0

    # Now scaffold clean
    result = runner.invoke(
        app,
        ["scaffold", "clean", "-c", str(dst / "dataset.yml"), "--dry-run"],
    )
    assert result.exit_code == 0
    assert "Generated by toolkit scaffold clean" in result.output
    assert "SELECT" in result.output
