-- Generated by toolkit scaffold clean
-- Source: data/raw/demo/2024/bdap_resource.csv
-- Encoding: utf-8 | Delimiter: , | Decimal: ,
--
-- This is a FIRST DRAFT. Review and adjust before running.
-- Run: toolkit run clean -c dataset.yml

SELECT
    TRY_CAST("a" AS VARCHAR) AS a,
    TRY_CAST("b" AS VARCHAR) AS b
FROM read_csv('data/raw/demo/2024/bdap_resource.csv', delim=',', encoding='utf-8', decimal_separator=',', header=false, skip=1, auto_detect=false, columns={ 'a': 'VARCHAR', 'b': 'VARCHAR' })
